### ISSUE TITLE
Review Items

### ISSUE THREAD

**Issue by outragedhuman** [Up-North-Coding/jovian#96]
Review items for V when he returns from his trip. Merged without review due to time constraints.

- [x] #81 
- [x] #84
- [x] #88 
- [x] #89 
- [x] #102 
- [x] #103

Nathan review:

- [x] #81 
  - [x] Needs another review from v, don't understand one point
- [x] #84
- [x] #88 
  - [x] Needs another review from v, tracking concern 
- [x] #89 
- [x] #102 
- [x] #103
  - [x] Need to discuss approaches to collecting additional field data in seed collection dialogs

**Comment by vwalsh** [comment]
reviewed fyi, comments added
